# Generated by Django 3.2.4 on 2024-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='has_card',
            field=models.BooleanField(default=False),
        ),
    ]
