# Generated by Django 3.2.4 on 2024-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='amount',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='currency',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='plan',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
