# Generated by Django 3.2.4 on 2024-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20240317_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
