# Generated by Django 3.2.4 on 2024-03-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_canclesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='canclesubscription',
            name='customer_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.customerpayment'),
            preserve_default=False,
        ),
    ]
