# Generated by Django 3.2.4 on 2024-03-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_canclesubscription_customer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='canclesubscription',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
