# Generated by Django 3.2.4 on 2024-03-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_canclesubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='card_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
