# Generated by Django 3.2.4 on 2024-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content_uuid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
