# Generated by Django 3.2.4 on 2024-09-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_content_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content_uuid',
            new_name='content',
        ),
    ]
