# Generated by Django 3.2.4 on 2024-09-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_content_uuid_feedback_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
