# Generated by Django 3.2.4 on 2024-04-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_userdailychecklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdailychecklist',
            old_name='seleted',
            new_name='selected',
        ),
    ]
