# Generated by Django 3.2.4 on 2024-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_rename_seleted_userdailychecklist_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailychecklist',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
