# Generated by Django 3.2.4 on 2024-05-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_dailychecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailychecklist',
            name='selected',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
