# Generated by Django 3.2.4 on 2024-05-26 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_userdailychecklist_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdailychecklist',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='userdailychecklist',
            name='user',
        ),
        migrations.AddField(
            model_name='dailychecked',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.userdailychecklist'),
        ),
        migrations.AddField(
            model_name='dailychecked',
            name='selected',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
