# Generated by Django 3.2.4 on 2024-05-26 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20240526_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecked',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
