# Generated by Django 3.2.4 on 2024-05-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_dailychecked_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterchecklist',
            name='options',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
