# Generated by Django 3.2.4 on 2024-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_userdailychecklist_master_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterchecklist',
            name='options',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
