# Generated by Django 3.2.4 on 2024-10-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_alter_masterchecklist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychecked',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='dailychecked',
            name='master_category',
        ),
        migrations.RemoveField(
            model_name='dailychecked',
            name='selected',
        ),
        migrations.AddField(
            model_name='dailychecked',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
