# Generated by Django 3.2.4 on 2024-10-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_lastcoursecontent'),
        ('checklist', '0015_auto_20241011_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecked',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.mastercategory'),
        ),
    ]
