# Generated by Django 3.2.4 on 2024-08-26 05:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_alter_content_channel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaChannel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', ckeditor.fields.RichTextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaChannelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('media_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_channel.mediachannel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mediachannellike',
            index=models.Index(fields=['timestamp'], name='media_chann_timesta_d25195_idx'),
        ),
        migrations.AddIndex(
            model_name='mediachannellike',
            index=models.Index(fields=['user'], name='media_chann_user_id_1aab31_idx'),
        ),
        migrations.AddIndex(
            model_name='mediachannel',
            index=models.Index(fields=['timestamp'], name='media_chann_timesta_14a2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediachannel',
            index=models.Index(fields=['user'], name='media_chann_user_id_a7abe8_idx'),
        ),
    ]
