# Generated by Django 4.2 on 2024-11-14 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_channel', '0002_mediachannellike_unique_media_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaChannelNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('media_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_channel.mediachannel')),
                ('media_channel_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_channel.mediachannellike')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
