# Generated by Django 4.2 on 2024-11-14 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media_channel', '0003_mediachannelnotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediachannellike',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mediachannelnotifications',
            name='id',
        ),
        migrations.AddField(
            model_name='mediachannellike',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mediachannelnotifications',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
