# Generated by Django 4.2 on 2024-11-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_channel', '0004_remove_mediachannellike_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediachannellike',
            name='media_channel',
        ),
        migrations.RemoveField(
            model_name='mediachannellike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mediachannelnotifications',
            name='media_channel',
        ),
        migrations.RemoveField(
            model_name='mediachannelnotifications',
            name='media_channel_like',
        ),
        migrations.RemoveField(
            model_name='mediachannelnotifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='MediaChannel',
        ),
        migrations.DeleteModel(
            name='MediaChannelLike',
        ),
        migrations.DeleteModel(
            name='MediaChannelNotifications',
        ),
    ]
