# Generated by Django 4.2 on 2024-11-14 05:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_alter_content_channel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_channel', '0005_remove_mediachannellike_media_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaChannel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', ckeditor.fields.RichTextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaChannelLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('media_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_channel.mediachannel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaChannelNotifications',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('media_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_channel.mediachannel')),
                ('media_channel_like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_channel.mediachannellike')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mediachannellike',
            index=models.Index(fields=['timestamp'], name='media_chann_timesta_d25195_idx'),
        ),
        migrations.AddIndex(
            model_name='mediachannellike',
            index=models.Index(fields=['user'], name='media_chann_user_id_1aab31_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediachannellike',
            constraint=models.UniqueConstraint(fields=('media_channel', 'user'), name='unique_media_like'),
        ),
        migrations.AddIndex(
            model_name='mediachannel',
            index=models.Index(fields=['timestamp'], name='media_chann_timesta_14a2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediachannel',
            index=models.Index(fields=['user'], name='media_chann_user_id_a7abe8_idx'),
        ),
    ]
