# Generated by Django 3.2.4 on 2024-09-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_uuid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='support',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_support_user'),
        ),
    ]
