# Generated by Django 3.2.4 on 2024-09-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_support_unique_support_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
