# Generated by Django 3.2.4 on 2024-10-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffel',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
