# Generated by Django 3.2.4 on 2024-04-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPollQuetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpoll',
            name='master_poll',
        ),
        migrations.RemoveField(
            model_name='userpoll',
            name='message',
        ),
        migrations.DeleteModel(
            name='MasterPoll',
        ),
        migrations.AddField(
            model_name='masterpolloption',
            name='poll_quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.masterpollquetion'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='poll_quetion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.masterpollquetion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpoll',
            name='selected_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.masterpolloption'),
            preserve_default=False,
        ),
    ]
