# Generated by Django 3.2.4 on 2024-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20240425_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpolloption',
            name='option',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='masterpollquetion',
            name='quetion',
            field=models.CharField(max_length=255),
        ),
    ]
