# Generated by Django 3.2.4 on 2024-04-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20240425_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='poll_quetion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.masterpollquetion'),
        ),
    ]
