# Generated by Django 3.2.4 on 2024-04-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_userpoll_poll_quetion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='poll_quetion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.masterpollquetion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpoll',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.masterpolloption'),
        ),
    ]
