# Generated by Django 3.2.4 on 2024-08-26 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blackhall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackhallchat',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='blackhallchat',
            name='id',
        ),
        migrations.AlterField(
            model_name='blackhallchat',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='blackhallchat',
            index=models.Index(fields=['timestamp'], name='blackhall_b_timesta_dfbf3b_idx'),
        ),
        migrations.AddIndex(
            model_name='blackhallchat',
            index=models.Index(fields=['user'], name='blackhall_b_user_id_dcc868_idx'),
        ),
    ]
