# Generated by Django 3.2.4 on 2024-09-28 06:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackhall', '0002_auto_20240826_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackhallchat',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
