# Generated by Django 3.2.4 on 2024-01-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20240124_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
