# Generated by Django 3.2.4 on 2024-02-22 01:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_favoritecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
