# Generated by Django 3.2.4 on 2024-02-22 01:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20240222_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
