# Generated by Django 3.2.4 on 2024-02-22 01:08

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20240222_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=channel.models.course_pic_path),
        ),
    ]
