# Generated by Django 3.2.4 on 2024-04-12 22:58

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_mastercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercategory',
            name='category_pic',
            field=models.FileField(blank=True, null=True, upload_to=channel.models.master_category_pic_path),
        ),
    ]
