# Generated by Django 3.2.4 on 2024-04-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_alter_mastercategory_category_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.mastercategory'),
        ),
    ]
