# Generated by Django 3.2.4 on 2024-04-18 21:56

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_category_master_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategory',
            name='category_pic2',
            field=models.FileField(blank=True, null=True, upload_to=channel.models.master_category_pic_2_path),
        ),
    ]
