# Generated by Django 3.2.4 on 2024-08-26 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0014_mastercategory_category_pic2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content_uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
