# Generated by Django 3.2.4 on 2024-01-13 04:03

import ckeditor.fields
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_otp', models.IntegerField(blank=True, null=True)),
                ('email_otp_validity', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('bio', ckeditor.fields.RichTextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user.models.avatar_path)),
                ('background', models.ImageField(blank=True, null=True, upload_to=user.models.background_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('coin', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, null=True, related_name='cutom_user_group', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
