# Generated by Django 3.2.4 on 2024-01-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_to', models.CharField(max_length=50)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_validity', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
