# Generated by Django 3.2.4 on 2024-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20240221_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='verification_token',
            field=models.CharField(max_length=255),
        ),
    ]
