# Generated by Django 3.2.4 on 2024-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_emailverification_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fa_type',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20),
        ),
    ]
