# Generated by Django 3.2.4 on 2024-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20240227_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fa_type',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='code', max_length=20),
        ),
    ]
