# Generated by Django 3.2.4 on 2024-03-03 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20240227_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fa_type',
            field=models.CharField(choices=[('code', 'Code'), ('email', 'Email')], default='code', max_length=20),
        ),
        migrations.CreateModel(
            name='FAVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_code', models.CharField(max_length=255)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('email_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
