# Generated by Django 3.2.4 on 2024-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20240303_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_coins_award_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
