# Generated by Django 3.2.4 on 2024-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_last_coins_award_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
    ]
