# Generated by Django 3.2.4 on 2024-04-27 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20240425_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to=user.models.wallpaper_path)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_purchase', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
