# Generated by Django 3.2.4 on 2024-04-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_userwallpaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallPaper',
        ),
    ]
