# Generated by Django 3.2.4 on 2024-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userwallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallpaper',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
