# Generated by Django 3.2.4 on 2024-04-27 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_userwallpaper_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallpaper',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
