# Generated by Django 3.2.4 on 2024-04-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20240427_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchesedemoji',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpurchesedtune',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
