# Generated by Django 3.2.4 on 2024-04-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20240427_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchesedemoji',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpurchesedtune',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userwallpaper',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
