# Generated by Django 3.2.4 on 2024-04-27 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20240427_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchesedemoji',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userpurchesedtune',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
