# Generated by Django 3.2.4 on 2024-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20240427_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_booster',
            field=models.BooleanField(default=False),
        ),
    ]
