# Generated by Django 3.2.4 on 2024-06-22 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_selected_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tune', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
