# Generated by Django 3.2.4 on 2024-07-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_tune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchesedtune',
            name='tune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tune'),
        ),
    ]
