# Generated by Django 3.2.4 on 2024-09-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20240911_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_picture',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
