# Generated by Django 3.2.4 on 2024-09-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_user_ai_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
